### ISSUE TITLE
noctua dependency issue

### ISSUE THREAD

**Issue by ltd-pa** [moj-analytical-services/Rdbtools#25]
Hi just installed this package into a new project and had an error for the first time:

`renv::install("moj-analytical-services/Rdbtools")`

This gave an error:

```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘noctua’ 2.6.2 is being loaded, but <= 2.6.1 is required
```

A workaround was to install an older version of the required dependency using:

`renv::install("noctua@2.6.1")`

Then the original command succeeded: 

`renv::install("moj-analytical-services/Rdbtools")`

**Comment by pjrh-moj** [comment]
This appears to be a feature of `renv` where it doesn't respect the requirements of the DESCRIPTION file when a package is installed from github.  I haven't been able to fix this.

In the short term, I'll make the install instructions more explicit so people install `noctua` as you suggest with the correct version.  In the longer term, I need to investigate how we can allow newer versions of `noctua` to power `Rdbtools` - the issue is that v2.6.2 changes the permissions required to include new ones which aren't on our accounts by default, and I haven't explored whether that is something that can change.

**Comment by ltd-pa** [comment]
Thanks for maintaining, really useful package!

**Comment by pjrh-moj** [comment]
Thanks!

I'll keep this issue open as a record because it is going to confuse people I expect - but something that you would hope `renv` would one day fix.

At some point in the future we'll have to consider whether using an old version of `noctua` works...  I just don't want to give up my `dbplyr` code yet!
